/* Real exercise photos, keyed by exercise id.
   Source: Free Exercise DB (https://github.com/yuhonas/free-exercise-db), released under The Unlicense (public domain).
   Photos are bundled locally with the app. Original source URLs remain in this registry for provenance.
   Every mapped image URL was fetched on VERIFIED_AT: HTTP 200, content-type image/jpeg. The dataset entry was matched to the move by name
   and equipment ("exact" = same movement; "close" = the nearest variant, labelled as such in the UI).
   Moves with no matching photo are in NO_PHOTO and keep the written steps. */

export type ExImage = {
  dbId: string;
  name: string;
  equipment: string;
  match: "exact" | "close";
  /** [start, end] */
  images: string[];
  source: "free-exercise-db";
  license: "Unlicense";
  verifiedAt: string;
};

export const VERIFIED_AT = "2026-10-08";

export const PHOTO_SOURCE = {
  id: "free-exercise-db",
  name: "Free Exercise DB",
  url: "https://github.com/yuhonas/free-exercise-db",
  license: "The Unlicense (public domain)",
  licenseUrl: "https://github.com/yuhonas/free-exercise-db/blob/main/LICENSE.md",
  attribution: "Photos: Free Exercise DB (yuhonas/free-exercise-db), public domain under The Unlicense.",
} as const;

export const EX_IMAGES: Record<string, ExImage> = {
  "dead-bug": { dbId: "Dead_Bug", name: "Dead Bug", equipment: "body only", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "band-walks": { dbId: "Monster_Walk", name: "Monster Walk", equipment: "bands", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Monster_Walk/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Monster_Walk/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "plank": { dbId: "Plank", name: "Plank", equipment: "body only", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "pallof": { dbId: "Pallof_Press", name: "Pallof Press", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pallof_Press/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pallof_Press/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "assisted-pullup": { dbId: "Band_Assisted_Pull-Up", name: "Band Assisted Pull-Up", equipment: "other", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "neutral-pullup": { dbId: "V-Bar_Pullup", name: "V-Bar Pullup", equipment: "body only", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Bar_Pullup/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Bar_Pullup/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "chest-supported-row": { dbId: "Dumbbell_Incline_Row", name: "Dumbbell Incline Row", equipment: "dumbbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Incline_Row/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Incline_Row/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "half-kneeling-pulldown": { dbId: "One_Arm_Lat_Pulldown", name: "One Arm Lat Pulldown", equipment: "cable", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One_Arm_Lat_Pulldown/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One_Arm_Lat_Pulldown/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "face-pull": { dbId: "Face_Pull", name: "Face Pull", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "straight-arm-pulldown": { dbId: "Rope_Straight-Arm_Pulldown", name: "Rope Straight-Arm Pulldown", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rope_Straight-Arm_Pulldown/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rope_Straight-Arm_Pulldown/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "reverse-crunch": { dbId: "Reverse_Crunch", name: "Reverse Crunch", equipment: "body only", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Crunch/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Crunch/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "cable-crunch": { dbId: "Cable_Crunch", name: "Cable Crunch", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "hack-squat": { dbId: "Hack_Squat", name: "Hack Squat", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "heel-elevated-goblet": { dbId: "Goblet_Squat", name: "Goblet Squat", equipment: "kettlebells", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "bulgarian-split-squat": { dbId: "Split_Squat_with_Dumbbells", name: "Split Squat with Dumbbells", equipment: "dumbbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Split_Squat_with_Dumbbells/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Split_Squat_with_Dumbbells/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "leg-press": { dbId: "Leg_Press", name: "Leg Press", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "leg-extension": { dbId: "Leg_Extensions", name: "Leg Extensions", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "standing-calf-raise": { dbId: "Standing_Calf_Raises", name: "Standing Calf Raises", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "incline-db-press": { dbId: "Incline_Dumbbell_Press", name: "Incline Dumbbell Press", equipment: "dumbbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "machine-chest-press": { dbId: "Machine_Bench_Press", name: "Machine Bench Press", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bench_Press/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bench_Press/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "weighted-pushup": { dbId: "Pushups", name: "Pushups", equipment: "body only", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "low-high-fly": { dbId: "Low_Cable_Crossover", name: "Low Cable Crossover", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Low_Cable_Crossover/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Low_Cable_Crossover/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "cable-lateral-raise": { dbId: "Standing_Low-Pulley_Deltoid_Raise", name: "Standing Low-Pulley Deltoid Raise", equipment: "cable", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Low-Pulley_Deltoid_Raise/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Low-Pulley_Deltoid_Raise/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "overhead-rope-triceps": { dbId: "Cable_Rope_Overhead_Triceps_Extension", name: "Cable Rope Overhead Triceps Extension", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "hip-thrust": { dbId: "Barbell_Hip_Thrust", name: "Barbell Hip Thrust", equipment: "barbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "leg-curl": { dbId: "Seated_Leg_Curl", name: "Seated Leg Curl", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "lying-leg-curl": { dbId: "Lying_Leg_Curls", name: "Lying Leg Curls", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "reverse-lunge": { dbId: "Dumbbell_Rear_Lunge", name: "Dumbbell Rear Lunge", equipment: "dumbbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Rear_Lunge/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Rear_Lunge/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "box-step-up": { dbId: "Dumbbell_Step_Ups", name: "Dumbbell Step Ups", equipment: "dumbbell", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "back-extension-45": { dbId: "Hyperextensions_Back_Extensions", name: "Hyperextensions (Back Extensions)", equipment: "other", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hyperextensions_Back_Extensions/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hyperextensions_Back_Extensions/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "seated-calf-raise": { dbId: "Seated_Calf_Raise", name: "Seated Calf Raise", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "shoulder-press": { dbId: "Dumbbell_Shoulder_Press", name: "Dumbbell Shoulder Press", equipment: "dumbbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "machine-shoulder-press": { dbId: "Machine_Shoulder_Military_Press", name: "Machine Shoulder (Military) Press", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Military_Press/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Military_Press/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "reverse-pec-deck": { dbId: "Reverse_Machine_Flyes", name: "Reverse Machine Flyes", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "y-raise": { dbId: "Dumbbell_Scaption", name: "Dumbbell Scaption", equipment: "dumbbell", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Scaption/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Scaption/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "ez-curl": { dbId: "EZ-Bar_Curl", name: "EZ-Bar Curl", equipment: "e-z curl bar", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "incline-db-curl": { dbId: "Incline_Dumbbell_Curl", name: "Incline Dumbbell Curl", equipment: "dumbbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "rope-pressdown": { dbId: "Triceps_Pushdown_-_Rope_Attachment", name: "Triceps Pushdown - Rope Attachment", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown_-_Rope_Attachment/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown_-_Rope_Attachment/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "farmer-carry": { dbId: "Farmers_Walk", name: "Farmer's Walk", equipment: "other", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Farmers_Walk/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Farmers_Walk/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "adductor-machine": { dbId: "Thigh_Adductor", name: "Thigh Adductor", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Adductor/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Adductor/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "sumo-goblet": { dbId: "Plie_Dumbbell_Squat", name: "Plie Dumbbell Squat", equipment: "dumbbell", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plie_Dumbbell_Squat/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plie_Dumbbell_Squat/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "pec-deck": { dbId: "Butterfly", name: "Butterfly", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "incline-machine-press": { dbId: "Leverage_Incline_Chest_Press", name: "Leverage Incline Chest Press", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Incline_Chest_Press/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Incline_Chest_Press/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "high-low-fly": { dbId: "Cable_Crossover", name: "Cable Crossover", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "wrist-curl": { dbId: "Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench", name: "Palms-Up Dumbbell Wrist Curl Over A Bench", equipment: "dumbbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "hammer-curl": { dbId: "Hammer_Curls", name: "Hammer Curls", equipment: "dumbbell", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "band-pull-apart": { dbId: "Band_Pull_Apart", name: "Band Pull Apart", equipment: "bands", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Pull_Apart/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Pull_Apart/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "cable-external-rotation": { dbId: "External_Rotation_with_Cable", name: "External Rotation with Cable", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/External_Rotation_with_Cable/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/External_Rotation_with_Cable/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "lat-pulldown": { dbId: "Wide-Grip_Lat_Pulldown", name: "Wide-Grip Lat Pulldown", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "seated-cable-row": { dbId: "Seated_Cable_Rows", name: "Seated Cable Rows", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "tbar-chest-supported": { dbId: "Lying_T-Bar_Row", name: "Lying T-Bar Row", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "side-plank": { dbId: "Side_Bridge", name: "Side Bridge", equipment: "body only", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Bridge/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Bridge/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "hanging-knee-raise": { dbId: "Knee_Hip_Raise_On_Parallel_Bars", name: "Knee/Hip Raise On Parallel Bars", equipment: "other", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Knee_Hip_Raise_On_Parallel_Bars/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Knee_Hip_Raise_On_Parallel_Bars/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "cable-woodchop": { dbId: "Standing_Cable_Wood_Chop", name: "Standing Cable Wood Chop", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Cable_Wood_Chop/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Cable_Wood_Chop/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "glute-bridge": { dbId: "Butt_Lift_Bridge", name: "Butt Lift (Bridge)", equipment: "body only", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butt_Lift_Bridge/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butt_Lift_Bridge/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "cable-pull-through": { dbId: "Pull_Through", name: "Pull Through", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pull_Through/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pull_Through/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "sl-glute-bridge": { dbId: "Single_Leg_Glute_Bridge", name: "Single Leg Glute Bridge", equipment: "body only", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "ball-leg-curl": { dbId: "Ball_Leg_Curl", name: "Ball Leg Curl", equipment: "exercise ball", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ball_Leg_Curl/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ball_Leg_Curl/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "nordic-curl": { dbId: "Natural_Glute_Ham_Raise", name: "Natural Glute Ham Raise", equipment: "body only", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Natural_Glute_Ham_Raise/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Natural_Glute_Ham_Raise/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "leg-press-narrow": { dbId: "Narrow_Stance_Leg_Press", name: "Narrow Stance Leg Press", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Narrow_Stance_Leg_Press/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Narrow_Stance_Leg_Press/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "sl-calf-raise-press": { dbId: "Calf_Press_On_The_Leg_Press_Machine", name: "Calf Press On The Leg Press Machine", equipment: "machine", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Press_On_The_Leg_Press_Machine/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Press_On_The_Leg_Press_Machine/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "skull-crusher": { dbId: "EZ-Bar_Skullcrusher", name: "EZ-Bar Skullcrusher", equipment: "e-z curl bar", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "close-grip-pushup": { dbId: "Push-Ups_-_Close_Triceps_Position", name: "Push-Ups - Close Triceps Position", equipment: "body only", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Ups_-_Close_Triceps_Position/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Ups_-_Close_Triceps_Position/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "preacher-curl": { dbId: "Machine_Preacher_Curls", name: "Machine Preacher Curls", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Preacher_Curls/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Preacher_Curls/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "cable-shrug": { dbId: "Cable_Shrugs", name: "Cable Shrugs", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Shrugs/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Shrugs/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "cable-front-raise": { dbId: "Front_Cable_Raise", name: "Front Cable Raise", equipment: "cable", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Cable_Raise/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Cable_Raise/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "chest-supported-rear-fly": { dbId: "Dumbbell_Lying_Rear_Lateral_Raise", name: "Dumbbell Lying Rear Lateral Raise", equipment: "dumbbell", match: "close", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lying_Rear_Lateral_Raise/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lying_Rear_Lateral_Raise/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "pushup": { dbId: "Pushups", name: "Pushups", equipment: "body only", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
  "reverse-hyper-light": { dbId: "Reverse_Hyperextension", name: "Reverse Hyperextension", equipment: "machine", match: "exact", images: ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Hyperextension/0.jpg", "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Hyperextension/1.jpg"], source: "free-exercise-db", license: "Unlicense", verifiedAt: VERIFIED_AT },
};

/** Deliberate fallbacks: no matching real photo. Reason is shown nowhere in the UI; it documents the choice. */
export const NO_PHOTO: Record<string, string> = {
  "ppt": "PT floor drill. The open dataset has no matching lying pelvic-tilt photo.",
  "pt-shoulder-flexion": "PT floor drill. No matching photo in the open dataset.",
  "bird-dog": "No bird dog photo in the open dataset.",
  "bracing-marches": "PT drill. No matching photo in the open dataset.",
  "clamshell": "No clamshell photo in the open dataset.",
  "single-leg-stand": "PT balance drill. No matching photo in the open dataset.",
  "seated-pigeon": "The only seated-glute entry needs a partner, so it is not the same move.",
  "suitcase-carry": "The dataset only has the two-handed farmer walk, which is a different carry.",
  "mobility-flow": "A time window in the PDF, not one movement.",
  "zone2": "Cardio pace guidance, not a movement.",
  "tuesday-cardio": "Cardio choice, not a single movement.",
  "wednesday-cardio": "Cardio choice, not a single movement.",
  "saturday-cardio": "Cardio choice, not a single movement.",
  "battle-rope-squat": "No battle-rope squat photo in the open dataset.",
  "incline-shrug": "No chest-supported incline shrug photo in the open dataset.",
  "tibialis-raise": "No tibialis raise photo in the open dataset.",
  "landmine-press": "No one-arm landmine press photo in the open dataset.",
  "assisted-dip": "The dataset dip machine is a seated press, not the assisted dip machine.",
  "machine-hip-thrust": "No machine hip thrust photo in the open dataset.",
  "bstance-rdl": "No B-stance RDL photo in the open dataset.",
  "cable-hip-abduction": "No cable hip abduction photo in the open dataset.",
  "btb-lateral-raise": "No behind-the-back cable raise photo in the open dataset.",
  "cross-body-cable-ext": "No cross-body cable extension photo in the open dataset.",
  "dead-hang": "No two-handed dead hang photo in the open dataset.",
  "wall-sit": "No wall sit photo in the open dataset.",
  "machine-lateral-raise": "No machine lateral raise photo in the open dataset.",
  "side-lying-abduction": "The dataset side leg raise is standing, not side-lying.",
  "bird-dog-hold": "No bird dog photo in the open dataset.",
};

export function photosFor(exerciseId: string): ExImage | undefined {
  const entry = EX_IMAGES[exerciseId];
  return entry ? { ...entry, images: entry.images.map((_, index) => `/media/exercises/${exerciseId}-${index}.jpg`) } : undefined;
}
